### ISSUE TITLE
Update to use github actions

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Control.AsyncSeq#129]
1. I've removed travis support 

2. I've enabled github actions

We still have an AppVeyor action that is useful as it builds and tests for fable. We should move this over to GitHub actions I think

```
environment:
  CLI_VERSION: 3.1.301
image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 14
  - yarn --cwd tests/fable --cache-folder=.cache/yarn --no-progress --pure-lockfile
cache:
  - tests/fable/.cache/yarn
build_script:
  - cmd: build.cmd
test: off
test_script:
  - yarn --cwd tests/fable test
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
```
